package ch13java6thedition;
import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 * 2. Image Viewer
 * 
 * Write an application that allows the user to view image files. 
 * The application should use either a button or a menu item 
 * that displays a file chooser. When the user selects an image
 * file, it should be loaded and displayed. 
 * 
 * @author craig
 */
public class ImageViewer extends JFrame {
	
	private final JFileChooser fileChooser = null;
	private ImageIcon image;
	private JMenuItem openItem;
	private JMenu fileMenu;
	private JMenuBar bar;
	private JPanel panel;
	private JLabel messageLabel;
	private JLabel imageLabel;
	private final int WINDOW_WIDTH = 500;
	private final int WINDOW_HEIGHT = 250;


	/**
	 * Constructor.
	 */
	public ImageViewer() {

		// Set the title for the window
		setTitle("Image Viewer");

		// Specify an action for the close button
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		// Set the location of the window
		setLocation(500, 250);

		// Create the main message
		messageLabel = new JLabel
		("Use the File tab to choose a picture to view.", SwingConstants.CENTER);

		// Set the message's preferred size
		messageLabel.setPreferredSize(
			new Dimension(WINDOW_WIDTH, WINDOW_HEIGHT));

		// Add the label
		add(messageLabel);

		// Build the menu bar
		buildMenuBar();

		// Pack and display the window
		pack();
		setVisible(true);

	}

	/**
	 * The buildMenuBar builds the menu bar.
	 */
	public void buildMenuBar() {

		// Create the menu bar
		bar = new JMenuBar();

		// Create a JMenu object for the File menu
		fileMenu = new JMenu("File");
		openItem = new JMenuItem("Open a File");
		fileMenu.add(openItem);
		openItem.addActionListener(new ImageListener());

		bar.add(fileMenu);
		
		// Set the bar
		setJMenuBar(bar);

	}

	/**
	 * Private inner class ImageListener handles the 
	 * events generated by the File menu.
	 */
	private class ImageListener implements ActionListener {

		public void actionPerformed(ActionEvent e) {

			JFileChooser fileChooser = new JFileChooser();
			int status = fileChooser.showOpenDialog(openItem);

			if (status == JFileChooser.APPROVE_OPTION) {

				File selectedFile = fileChooser.getSelectedFile();
				String fileName = selectedFile.getPath();
				image = new ImageIcon(fileName);
				imageLabel = new JLabel(image);
				messageLabel.setText(null);
				add(imageLabel);
				pack();

			}

		}

	}
	/**
	 * The main method creates an instance of the class
	 * causing it to display its window.
	 */
	public static void main(String[]args) {

		new ImageViewer();

	}
}
