package ch13java6thedition;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
/**
 * This is programming challenge #1.
 * 
 * Create an application that allows you to enter the amount of a 
 * purchase and then displays the amount of sales tax on that purchase.
 * Use a slider to adjust the tax rate between 0 and 10 percent.
 * 
 * @author craig
 */
public class ScrollableTaxCalculator extends JFrame {
	
	private JTextField purchaseField;	
	private final JTextField taxField;
	private final JLabel purchaseLabel;
	private final JLabel taxLabel;
	private final JPanel sliderPanel;
	private final JPanel taxPanel;
	private final JPanel purchasePanel;
	private final JSlider slider;

	/**
	 * Constructor.
	 */
	public ScrollableTaxCalculator() {

		// Set the window's title
		setTitle("Scrollable Tax Calculator");

		// Specify an action for the close button
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		// Specify location for the window
		setLocation(500, 250);

		// Specify a layout manager
		setLayout(new GridLayout(3, 1));

		// Create the labels
		purchaseLabel = new JLabel("Purchase Price: $");
		taxLabel = new JLabel("Tax: $");

		// Create the read-only text fields
		purchaseField = new JTextField("0.00", 10);
		purchaseField.setEditable(true);

		taxField = new JTextField("0.00", 10);
		taxField.setEditable(false);

		// Create the slider
		slider = new JSlider(JSlider.HORIZONTAL, 0, 10, 0);
		slider.setMajorTickSpacing(1);
		slider.setPaintTicks(true);
		slider.setPaintLabels(true);
		slider.addChangeListener(new SliderListener());

		// Create the panels 
		purchasePanel = new JPanel();
		taxPanel = new JPanel();
		sliderPanel = new JPanel();
			
		// Add the components to the panels
		purchasePanel.add(purchaseLabel);
		purchasePanel.add(purchaseField);
		taxPanel.add(taxLabel);
		taxPanel.add(taxField);
		sliderPanel.add(slider);

		// Add the panels to the content pane
		add(purchasePanel);
		add(taxPanel);
		add(sliderPanel);
		
		// Pack and display the window
		pack();
		setVisible(true);
	}

	/**
	 * Private inner class to hold the events generated by the 
	 * action of the slider.
	 */
	private class SliderListener implements ChangeListener {

		public void stateChanged(ChangeEvent e) {

			double purchase, tax, purchaseTax;

			tax = slider.getValue();
			purchase = Double.parseDouble(purchaseField.getText());
			purchaseTax = (tax * .01) * purchase;
			taxField.setText(String.format("%,.2f", purchaseTax));

		}

	}

	/**
	 * Main method creates an instance of the ScrollableTaxCalculator
	 * class, causing it to display its window.
	 */
	public static void main(String[]args) {

		new ScrollableTaxCalculator();
		
	}

}
